http:
  host: 'localhost'
  port: 3000

api:
  prefix: 'api/v1'

db:
  postgres:
    type: 'postgres'
    host: 'localhost'
    port: 5432
    name: 'postgres'
    username: 'postgres'
    password: 'admin'
    ssl: false
    logging: false
jwt:
  secret: 'hegi-microservice'
  expiry: '1h'

swagger:
  title: 'HDFC_ERGO'
  description: 'API Documentation for the app HDFC_ERGO'
  version: '1.0.0'
  auth: 
     type: 'http'
     schema: 'bearer'
     bearerformat: 'JWT'
     name: 'JWT'
     description: 'Enter JWT token'
     in: 'header'
     
